---
apiVersion: "kustomize.config.k8s.io/v1beta1"
kind: "Kustomization"
namespace: "kube-system"

resources:
  - "helm-repository.yaml"
  - "helm-release.yaml"
  # Allow the serviceuser to manage secrets
  - "rbac.yaml"

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: "csi-driver-config-input"
    files:
      - "values.yaml=values.yaml"




# helm repo add secrets-store-csi-driver https://kubernetes-sigs.github.io/secrets-store-csi-driver/charts
# helm install csi-secrets-store secrets-store-csi-driver/secrets-store-csi-driver --namespace kube-system