---
apiVersion: "kustomize.config.k8s.io/v1beta1"
kind: "Kustomization"
namespace: "awx"

resources:
  # - "namespace.yaml"
  - github.com/ansible/awx-operator/config/default?ref=0.21.0
  - "awx.yaml"
  - "dbsettings.yaml"
  - "vaultconfig.yaml"
  - "dbdummy.yaml"

generatorOptions:
  disableNameSuffixHash: true

images:
  - name: quay.io/ansible/awx-operator
    newTag: 0.21.0
