---
apiVersion: v1
kind: Pod
metadata:
  name: ubuntu
  labels:
    app: ubuntu
  annotations:
    vault.hashicorp.com/agent-inject: "true"
    vault.hashicorp.com/agent-configmap: "awx-vault-config"
    # vault.hashicorp.com/agent-inject: "true"
    # vault.hashicorp.com/agent-inject-secret-foo: database/static-creds/awx
    # vault.hashicorp.com/role: awx
spec:
  serviceAccount: awx-demo
  containers:
  - name: ubuntu
    image: ubuntu:latest
    command: ["/bin/sleep", "3650d"]
    imagePullPolicy: IfNotPresent
  restartPolicy: Always
