apiVersion: v1
kind: ConfigMap
metadata:
  name: awx-vault-config
data:
  config.hcl: |
    vault {
      address = "http://vault.vault.svc.cluster.local:8200"
    }
    auto_auth {
      method {
        mount_path = "auth/kubernetes"
        type = "kubernetes"
        config = {
          role = "awx"
        }
      }
      sink "file" {
          config = {
              path = "/home/vault/.vault-token"
          }
      }
    }
    exit_after_auth = false
    pid_file = "/home/vault/.pid"
    template {
      contents = <<EOT
        {{- with secret "database/static-creds/awx" }}
    DATABASES = {
      'default': {
        'ATOMIC_REQUESTS': True,
        'ENGINE': 'awx.main.db.profiled_pg',
        'NAME': 'awx',
        'USER': '{{ .Data.username }}',
        'PASSWORD': '{{.Data.password }}',
        'HOST': 'postgres.postgres.svc.cluster.local',
        'PORT': '5432',
        'OPTIONS': { 'sslmode': 'prefer',
                      'sslrootcert': '/etc/pki/tls/certs/ca-bundle.crt',
          },
      }
    }
        {{ end }}
      EOT
      destination = "/vault/secrets/database.py"
    }
  config-init.hcl: |
    vault {
      address = "http://vault.vault.svc.cluster.local:8200"
    }
    auto_auth {
      method {
        mount_path = "auth/kubernetes"
        type = "kubernetes"
        config = {
          role = "awx"
        }
      }
      sink "file" {
          config = {
              path = "/home/vault/.vault-token"
          }
      }
    }
    exit_after_auth = true
    pid_file = "/home/vault/.pid"
    template {
      contents = <<EOT
        {{- with secret "database/static-creds/awx" }}
    DATABASES = {
      'default': {
        'ATOMIC_REQUESTS': True,
        'ENGINE': 'awx.main.db.profiled_pg',
        'NAME': 'awx',
        'USER': '{{ .Data.username }}',
        'PASSWORD': '{{.Data.password }}',
        'HOST': 'postgres.postgres.svc.cluster.local',
        'PORT': '5432',
        'OPTIONS': { 'sslmode': 'prefer',
                      'sslrootcert': '/etc/pki/tls/certs/ca-bundle.crt',
          },
      }
    }
        {{ end }}
      EOT
      destination = "/vault/secrets/database.py"
    }
