---
apiVersion: "kustomize.config.k8s.io/v1beta1"
kind: "Kustomization"
namespace: "vault"

resources:
  - "namespace.yaml"
  - "vault-helmrepo.yaml"
  - "vault-helmrelease.yaml"


generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: "vault-values"
    files:
      - "vault-values.yaml"
