---
apiVersion: "helm.toolkit.fluxcd.io/v2beta1"
kind: "HelmRelease"
metadata:
  name: "vault"
spec:
  interval: "5m"
  releaseName: "vault"
  chart:
    spec:
      chart: "vault"
      version: "0.19.0"
      sourceRef:
        kind: "HelmRepository"
        name: "hashicorp"
        namespace: "vault"
      interval: "1m"
  valuesFrom:
    - kind: "ConfigMap"
      name: "vault-values"
      valuesKey: "vault-values.yaml"
