---
apiVersion: "kustomize.config.k8s.io/v1beta1"
kind: "Kustomization"
namespace: "postgres"

resources:
  - "namespace.yaml"
  - "dbconfig.yaml"
  - "volume.yaml"
  - "deployment.yaml"
  - "service.yaml"

generatorOptions:
  disableNameSuffixHash: true
